version: '2.24.3'  # Use the appropriate version for your Docker Compose file

services:
  service:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ../weferral
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4100/setup"]
      interval: 10s
      timeout: 5s
      retries: 10

  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3500:8080
    restart: always
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  pgdata:

