version: '2.24.3'  # Use the appropriate version for your Docker Compose file

services:
  service:
    build:
      context: .
      no_cache: true
    ports:
      - "3001:3001"
    volumes:
      - "./env:/usr/src/app/env"
    depends_on:
      database:
        condition: service_healthy
    environment:
      FRONTEND_URL: https://affiliate.shutterpress.io
      NODE_ENV: "production"
      BASE_PATH: "affiliate.shutterpress.io/"
      PORT: 3001

  frontend:
    build:
      context: ../weferral
      dockerfile: Dockerfile
      no_cache: true
    volumes:
      - "./../weferral/app:/usr/src/app"
      - "./../weferral/build:/usr/src/build"
    ports:
      - "4100:4100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4100/setup"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      NODE_ENV: "production"
      API_URL: "https://affiliate.shutterpress.io"
      BASE_PATH: "/"

  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_USER: weferral
      POSTGRES_PASSWORD: nigerianPrince123!
      POSTGRES_DB: weferral
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8991:8080

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    restart: always
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  pgdata:

